# workflow name
name: Auto Push

# master branch on push, auto run
on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  schedule:
    - cron: "* 12 * * *"
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 自动提交
        run: |
          git clone ${{ secrets.REPO }} ./
          curl -H 'Content-Type:text/plain' --data-binary @baidu_urls.txt "${{secrets.TOKEN}}"
